module 0xc60907825c5acd62e0ea6d66cd706256e8920d37cc6b61634e07fa0ce2e6a05c::collection_coin {
    struct COLLECTION_COIN has drop {
        dummy_field: bool,
    }

    fun init(arg0: COLLECTION_COIN, arg1: &mut 0x2::tx_context::TxContext) {
        let v0 = 0x2::tx_context::sender(arg1);
        let (v1, v2) = 0x2::coin::create_currency<COLLECTION_COIN>(arg0, 9, b"ART", b"Sui Art Collection", b"Collection token generated by Sui Art.", 0x1::option::none<0x2::url::Url>(), arg1);
        0x2::transfer::public_transfer<0x2::coin::TreasuryCap<COLLECTION_COIN>>(v1, v0);
        0x2::transfer::public_transfer<0x2::coin::CoinMetadata<COLLECTION_COIN>>(v2, v0);
    }

    // decompiled from Move bytecode v7
}

