module 0x4e0a3b37b12e36a279593d6499342140815c22884d2d3755084fb57a94cd064e::usdlp {
    struct USDLP has drop {
        dummy_field: bool,
    }

    fun init(arg0: USDLP, arg1: &mut 0x2::tx_context::TxContext) {
        let (v0, v1) = 0x2::coin::create_currency<USDLP>(arg0, 6, b"USDLP", b"USDC Yield lp", b"USDLP represents your proportional ownership of the vault and its performance.The vault is designed with a short lock-up period of 1 day, giving depositors greater flexibility over their capital. After the applicable lock-up period, users can request to withdraw liquidity.  A minimal performance fee is charged only on profits generated by the vault, allowing depositors to retain the majority of their returns.", 0x1::option::some<0x2::url::Url>(0x2::url::new_unsafe_from_bytes(b"https://aftermath.finance/coins/perpetuals/default.svg")), arg1);
        0x2::transfer::public_freeze_object<0x2::coin::CoinMetadata<USDLP>>(v1);
        0x2::transfer::public_transfer<0x2::coin::TreasuryCap<USDLP>>(v0, 0x2::tx_context::sender(arg1));
    }

    // decompiled from Move bytecode v7
}

