module 0x6c93edef36645f57e8a811afc3e85d98fd275f39044b93185a7a257309096c7c::badgarr {
    struct BADGARR has drop {
        dummy_field: bool,
    }

    fun init(arg0: BADGARR, arg1: &mut 0x2::tx_context::TxContext) {
        let (v0, v1) = 0x2::coin::create_currency<BADGARR>(arg0, 6, b"BADGARR", b"BADGAR", b"BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR BADGAR", 0x1::option::some<0x2::url::Url>(0x2::url::new_unsafe_from_bytes(b"https://api.movepump.com/uploads/photo_2024_09_15_08_41_02_0e3867a0c4.jpg")), arg1);
        0x2::transfer::public_transfer<0x2::coin::TreasuryCap<BADGARR>>(v0, 0x2::tx_context::sender(arg1));
        0x2::transfer::public_share_object<0x2::coin::CoinMetadata<BADGARR>>(v1);
    }

    // decompiled from Move bytecode v6
}

