module 0xd88e68d3ac06e4ebada92123ef7981a93028fe8ff9b81452ff1479bb6799a4fd::gegl {
    struct GEGL has drop {
        dummy_field: bool,
    }

    fun init(arg0: GEGL, arg1: &mut 0x2::tx_context::TxContext) {
        let (v0, v1) = 0x2::coin::create_currency<GEGL>(arg0, 9, b"GEGL", b"Gene_Flowe", b"Genofi - Generated by AI", 0x1::option::some<0x2::url::Url>(0x2::url::new_unsafe_from_bytes(b"https://file-walletapp.waveonsui.com/images/wave-pumps/c210a31f-0756-4aab-adda-0cd1ad1c335c.webp")), arg1);
        0x2::transfer::public_transfer<0x2::coin::TreasuryCap<GEGL>>(v0, 0x2::tx_context::sender(arg1));
        0x2::transfer::public_freeze_object<0x2::coin::CoinMetadata<GEGL>>(v1);
    }

    // decompiled from Move bytecode v6
}

