module 0x8f2635a9ba8de061f66e2cd3029714c3590f96e5707ee95fbd5d2aef3b947c46::suni {
    struct SUNI has drop {
        dummy_field: bool,
    }

    fun init(arg0: SUNI, arg1: &mut 0x2::tx_context::TxContext) {
        let (v0, v1) = 0x2::coin::create_currency<SUNI>(arg0, 6, b"SUNI", b"Unicorn AI On Sui", b"$Suni is #meme coin generated by #AI build on #Sui. Inspired $GOAT on #Solana.", 0x1::option::some<0x2::url::Url>(0x2::url::new_unsafe_from_bytes(b"https://r.turbos.finance/icon/1730952995730.gif")), arg1);
        0x2::transfer::public_freeze_object<0x2::coin::CoinMetadata<SUNI>>(v1);
        0x2::transfer::public_transfer<0x2::coin::TreasuryCap<SUNI>>(v0, 0x2::tx_context::sender(arg1));
    }

    // decompiled from Move bytecode v6
}

